import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { stages, useRescue } from './store';
export const colors = { ink: '#163B35', muted: '#6D7D77', green: '#176B50', pale: '#EAF3ED', orange: '#BA4A23', orangePale: '#FFF0E7', line: '#E1E8E2', background: '#F5F7F3' };
export function Icon({ name, color = colors.ink, size = 22 }) { return <Feather name={name} color={color} size={size}/>; }
export function Page({ children }) { return <SafeAreaView style={s.page} edges={['top', 'left', 'right']}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>{children}</ScrollView></SafeAreaView>; }
export function Heading({ title, subtitle }) { return <View style={{ gap: 7 }}><Text style={s.eyebrow}>TRẠM CỨU HỘ ĐỘNG VẬT</Text><Text accessibilityRole="header" style={s.title}>{title}</Text><Text style={s.body}>{subtitle}</Text></View>; }
export function Button({ label, onPress, secondary = false, disabled = false, icon }) { return <Pressable accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [s.button, secondary && s.secondary, (pressed || disabled) && { opacity: 0.55 }]}>{icon && <Icon name={icon} size={18} color={secondary ? colors.ink : '#fff'}/>}<Text style={[s.buttonText, secondary && { color: colors.ink }]}>{label}</Text></Pressable>; }
export function Section({ title, action, onPress }) { return <View style={s.row}><Text accessibilityRole="header" style={s.section}>{title}</Text>{action && <Pressable accessibilityRole="button" onPress={onPress} style={s.touch}><Text style={s.link}>{action}</Text><Icon name="arrow-right" size={16} color={colors.green}/></Pressable>}</View>; }
export function Badge({ label, urgent = false }) { return <View style={[s.badge, urgent && { backgroundColor: colors.orangePale }]}><Text style={[s.badgeText, urgent && { color: colors.orange }]}>{label}</Text></View>; }
export function MissionCard({ mission }) { const { user } = useRescue(); return <Pressable accessibilityRole="button" accessibilityLabel={`${mission.id}, ${mission.title}, ${stages[mission.stage]}`} onPress={() => router.push(`/mission/${mission.id}`)} style={({ pressed }) => [s.card, mission.priority === 'Khẩn cấp' && mission.stage < 5 && { borderLeftWidth: 4, borderLeftColor: colors.orange }, pressed && { opacity: 0.7 }]}><View style={s.row}><Badge label={mission.stage === 5 ? 'Hoàn tất' : mission.priority} urgent={mission.stage < 5 && mission.priority === 'Khẩn cấp'}/><Text style={s.small}>{mission.id} · {mission.time}</Text></View><Badge label={mission.leader === user.id ? 'Bạn là nhóm trưởng' : 'Bạn là thành viên'}/><Text style={s.cardTitle}>{mission.title}</Text><View style={s.inline}><Icon name="map-pin" size={16} color={colors.muted}/><Text style={[s.body, { flex: 1 }]}>{mission.address}</Text></View><View style={[s.row, s.cardFoot]}><View style={s.inline}><Icon name="users" size={16} color={colors.muted}/><Text style={s.small}>{mission.animal} · {mission.count} cá thể</Text></View><View style={s.inline}><Text style={s.link}>{mission.stage === 0 ? 'Xem nhiệm vụ' : stages[mission.stage]}</Text><Icon name="chevron-right" size={17} color={colors.green}/></View></View></Pressable>; }
export const s = StyleSheet.create({
    page: { flex: 1, backgroundColor: colors.background }, content: { width: '100%', maxWidth: 680, alignSelf: 'center', padding: 22, paddingBottom: 32, gap: 22 },
    title: { fontSize: 30, fontWeight: '800', color: colors.ink, letterSpacing: -0.8 }, eyebrow: { fontSize: 11, fontWeight: '800', letterSpacing: 1.6, color: colors.green },
    body: { fontSize: 14, lineHeight: 22, color: colors.muted }, small: { fontSize: 12, lineHeight: 18, color: colors.muted }, section: { fontSize: 19, fontWeight: '700', color: colors.ink },
    row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, flexWrap: 'wrap' }, inline: { flexDirection: 'row', alignItems: 'center', gap: 7 },
    card: { padding: 18, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line, borderRadius: 18, gap: 13 }, cardTitle: { fontSize: 18, fontWeight: '700', lineHeight: 26, color: colors.ink },
    cardFoot: { paddingTop: 13, borderTopWidth: 1, borderTopColor: colors.line }, badge: { alignSelf: 'flex-start', backgroundColor: colors.pale, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 7 }, badgeText: { color: colors.green, fontSize: 11, fontWeight: '700' },
    button: { minHeight: 52, paddingVertical: 14, paddingHorizontal: 18, backgroundColor: colors.green, borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 10 }, secondary: { backgroundColor: colors.pale, borderWidth: 1, borderColor: colors.line }, buttonText: { color: '#fff', fontSize: 15, fontWeight: '700' },
    link: { color: colors.green, fontSize: 12, fontWeight: '700' }, touch: { minHeight: 44, justifyContent: 'center', flexDirection: 'row', alignItems: 'center', gap: 6 },
    avatar: { width: 44, height: 44, borderRadius: 16, backgroundColor: colors.pale, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.green, fontWeight: '800', fontSize: 14 },
    empty: { padding: 30, gap: 12, alignItems: 'center', backgroundColor: '#fff', borderRadius: 18 }, input: { minHeight: 48, borderColor: colors.line, borderWidth: 1, borderRadius: 12, padding: 14, backgroundColor: '#fff', fontSize: 15, color: colors.ink },
});

